# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed381221ecd8700c5646f0db8cad2e2a918c573300b08a0603718329e1fc2843edc6062e442ab8422c6a80403ee03497b4b842afc703c790aeab953395af6915

test:
  secret_key_base: b02093e8934933421b61c4c25df7628d541051988c0536118321a3f5341ae8d26998578fd1bd0058ee4b0a02faf4402d3c27cf969946feede2ac62dbf813af51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
